// <auto-generated />
namespace ContactBook.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedlatanlngtoadress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedlatanlngtoadress));
        
        string IMigrationMetadata.Id
        {
            get { return "201911071118540_added lat an lng to adress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
